### ISSUE TITLE
Reboot to hekate option crashes atmosphere

### ISSUE THREAD

**Issue by pitrako** [AtlasNX/Kosmos-Toolbox#34]
![IMG_20201013_135441](https://user-images.githubusercontent.com/42267151/95857689-46bee500-0d5c-11eb-820e-28c4fadca6b8.jpg)

**Comment by cathery** [comment]
I believe you're getting a crash because you don't have the necessary payload file. It's a known issue and has been fixed in the dev branch already, the new changes just need to be compiled and published. For now, you can grab your hekate payload and put it in this path: `sdmc:/bootloader/update.bin`. This should fix the crash.

**Comment by pitrako** [comment]
Solved, thanks for the help.
